### PR TITLE
Re-added support for files when using Rainbow

### LINKED ISSUE #29: Files packaging does not work with Rainbow serialization provider
I tried packaging files and Rainbow items at once and it does not work. Files are not packaged as expected.

However, support for file serialization was added in commit [#3d677a22bef44f01420733d1f484c5222a6ea856](https://github.com/adoprog/Sitecore-Courier/commit/3d677a22bef44f01420733d1f484c5222a6ea856) by @rauljmz on September 9th, 2016.

I tracked the cause to commit [#8d53f99fb55aae5b548cfaccd2fda67b249ca722](https://github.com/adoprog/Sitecore-Courier/commit/8d53f99fb55aae5b548cfaccd2fda67b249ca722) on June 20th, 2017 which has an older parent ([#90b796c0feab5c0448852f6a91377b0ee62bdf72](https://github.com/adoprog/Sitecore-Courier/commit/90b796c0feab5c0448852f6a91377b0ee62bdf72) from August 23rd, 2016), and removed this support from the code.

### PR DESCRIPTION
**Pull request by jflheureux**
Fixes #29 

This modification was forgotten when the removed code was re-introduced in 2017.

### CODE REVIEW

**Comment by adoprog** [comment]
Thanks!

**Comment by jflheureux** [comment]
Thanks for merging my PR. Any chance of a new release including the fix on Chocolatey or PowerShell Gallery? It would be nice not to have to commit the exe and dlls in my repo to use Sitecore.Courier in my CI/CD process.

**Comment by adoprog** [comment]
@jflheureux will try to get both out this week

**Comment by adoprog** [comment]
@jflheureux I've published the release on GitHub but looks like Choco is having troubles reading .nupkg files at the moment. I'll try to upload it again in a week.

**Pull request merged**
