### PR TITLE
Add unversioned fields to the version and fix command line args

### PR DESCRIPTION
**Pull request by markgibbons25**
Unversioned fields were being excluded

### CODE REVIEW

**Comment by adoprog** [comment]
Sorry for the late response, I think changing collisionBehavior from 'c' to 'b' might break other people's builds relying on it. What do you think?

**Comment by markgibbons25** [comment]
I never ended up using courier in production because of the lack of support here, but I seem to remember the documentation said to use -b for collision behaviour and yet -c is implemented. Forgive me if I'm wrong, it's been over a year ago.

**Comment by adoprog** [comment]
Ah, that's sad to hear, I'm really sorry that I've missed this pull request. Please feel free to raise issues if you ever get back to it and encounter any difficulties. I'm actively using it in a few production projects now and it works really well.

**Comment by adoprog** [comment]
The issue is now fixed - https://github.com/adoprog/Sitecore-Courier/commit/32d5a1c09c105c3e224fe4c6193290b5222b1d89

Thanks for reporting it providing the fix! Pull request will now be closed.

**Pull request closed without merging**
